### ISSUE TITLE
Can't delete package from AC interface.

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Server/support#11]
Trying to remove a package by hand in the web interface doesn't seem to do anything.  I've used this before (with a different AC look/feel) without any problems, but right now, selecting a package and then using the dropdown Actions => Remove.  Doesn't do any thing.   This is with Chrom Version 47.0.2526.106 (64-bit) in an incognito window (no plugins). 
![screen shot 2015-12-28 at 4 52 18 pm](https://cloud.githubusercontent.com/assets/479480/12027439/b477c208-ad83-11e5-876e-41d7ff43a9aa.png)

Also fails on firefox.

Cheers,

Matt

**Comment by stephenakearns** [comment]
Thanks @flamingbear - looking into this.

**Comment by pelson** [comment]
:+1:

**Comment by stephenakearns** [comment]
FYI - issue has been reviewed and a pull request is opened to resolve the issue. Fix anticipated in next patch release (<2 weeks)

**Comment by jochym** [comment]
I confirm this issue. It is quite annoying - you cannot correct your mistakes...

**Comment by stephenakearns** [comment]
Fyi, a patch for this is in the works: code complete and working thru our validate and release process. 

-----Original Message-----

**Comment by dsludwig** [comment]
@flamingbear the fix for this issue has been released. Thank you for the report!
