### ISSUE TITLE
Most recent packages not sorted correctly

### ISSUE THREAD

**Issue by rmcgibbo** [Anaconda-Server/support#15]
I believe the "Most recent" packages sidebar on https://anaconda.org/<orgname> (e.g. https://anaconda.org/omnia) is just sorting the package names alphabetically, not in reverse chronological order. It's showing only the packages that begin with 'A', despite more recent packages being uploaded.

**Comment by stephenakearns** [comment]
thanks @rmcgibbo - we've resolved this - if this isn't fixed for you, please reopen and let me know.
