### ISSUE TITLE
Deleted package files still shown on web frontend

### ISSUE THREAD

**Issue by rainman110** [Anaconda-Server/support#16]
I deleted some of our package with the anaconda command

    anaconda remove DLR-SC/pythonocc-core/0.16.3dev

The files are still listed on https://anaconda.org/DLR-SC/pythonocc-core/files, but they are dead links and produce a 404.

**Comment by stephenakearns** [comment]
working on a fix - workaround: refresh page

**Comment by srossross** [comment]
@rafaelhbarros is this fixed in develop? I think there should be an attached PR right?

**Comment by rafaelhbarros** [comment]
@srossross I cannot recollect when I worked on this. Can you give me more details?

**Comment by dsludwig** [comment]
I believe that this was fixed in Anaconda-Server/Anaconda-server#1554

**Comment by rafaelhbarros** [comment]
Thanks, @dsludwig

**Comment by dsludwig** [comment]
@rainman110 it looks like this issue was fixed in the latest release. Thanks for reporting this issue with Anaconda Cloud! Let me know if you experience the problem again.
