### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by zaitsxl** [Anaconda-Server/support#17]
Hi,

we're trying to reset password for user with email y.smolyaninov@levi9.com via password reset webform. We tried several times over several days but no email with reset stuff is being received. Please check

Regards,
Alexander

**Comment by srossross** [comment]
Thank @zaitsxl, sorry for the late response. We are looking into this now

**Comment by srossross** [comment]
Hi Alexander after further inspection, the email address y.smolyaninov@levi9.com does not appear to be an email address in our database. You should be getting an error "Email does not Exist" when you try to reset your password.

**Comment by zaitsxl** [comment]
Hi Sean,

that's because we already managed to change it via support portal. Your
colleague responded first, sorry

2016-02-16 0:06 GMT+02:00 Sean Ross-Ross <notifications@github.com>:

> Hi Alexander after further inspection, the email address
> y.smolyaninov@levi9.com does not appear to be an email address in our
> database. You should be getting an error "Email does not Exist" when you
> try to reset your password.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/support/issues/17#issuecomment-184415179>
> .
>



-- 
In DOS we trust. Alexander Zaitsev
