### ISSUE TITLE
A-Cloud UI: No easy way to tell if packages or public or private

### ISSUE THREAD

**Issue by gmarkall** [Anaconda-Server/support#18]
In previous iterations of the user interface, a lock symbol appeared next to private packages. However, I can see no lock symbol or any other indication of privacy in the current UI - it can only be checked by looking at the package settings.

**Comment by srossross** [comment]
@gmarkall what page are you looking at?

**Comment by srossross** [comment]
NM: I see what you are talking about here: https://anaconda.org/sean/packages

**Comment by srossross** [comment]
I will try to do this in #1368

**Comment by srossross** [comment]
Closing this. please track it in Anaconda-Server/Anaconda-Server#1368
