### ISSUE TITLE
Creating a package requires manually entering a URL

### ISSUE THREAD

**Issue by gmarkall** [Anaconda-Server/support#19]
According to the docs, the way to create a new package is to visit https://anaconda.org/new - having to enter to URL yourself or navigate through the docs to do this seems a bit unfriendly - perhaps a link somewhere in the UI to create a new package would make for an easier experience?

**Comment by srossross** [comment]
@elecronwill can you remove the new link from the docs? 

@gmarkall we are not at a point  where creating a new package from the web UI is entirely useful. For now we are recommending creating packages from the command line only.

**Comment by gmarkall** [comment]
Is it possible to create a private package from the command line though? If so, how is that achieved? (I can't find how to do that from any docs I can find)

**Comment by electronwill** [comment]
The link was removed in https://github.com/Anaconda-Server/docs.anaconda.org/pull/244 .

**Comment by electronwill** [comment]
I'm also curious about Graham's question about creating private packages from the command line. I'll pay close attention to further discussion in this thread, and will add further info to the docs if appropriate.

**Comment by srossross** [comment]
By default you create a package when you run `anaconda upload ` or if you just want to register a package namespase (what the web UI did)  you can run `anaconda package --create [options]`

**Comment by electronwill** [comment]
I see that 'anaconda package' does have a '--private' option: http://docs.anaconda.org/cli.html#Package

**Comment by gmarkall** [comment]
From the anaconda client help for `package`:

```
privacy:
  --personal            Set the package access to personal This package will
                        be available only on your personal registries
  --private             Set the package access to private This package will
                        require authenticated access to install
```

The documentation for the `--private` flag is confusing, because `--private` implies to me that the package will be private, but the explanation suggests simply being authenticated to anaconda.org will be sufficient to access it (like I think we have for things like the MKL packages).

**Comment by electronwill** [comment]
Perhaps we could replace 'This package will require authenticated access to install' with 'To install a private package a user must be granted access to it and must use authentication'?

**Comment by gmarkall** [comment]
Or "requires authorized and authenticated access to install"?

**Comment by srossross** [comment]
:+1:

**Comment by electronwill** [comment]
OK, the change to the interactive help is merged and will be in the next release, and built into the docs site at the same time or very soon after.
