### ISSUE TITLE
pyhull

### ISSUE THREAD

**Issue by bwanaaa** [Anaconda-Server/support#2]
Pyhull is a wrapper for qhull, a library for the calculation of shapes.
`conda install pyhull`
 does not find anything.
`anaconda search -t conda pyhull`
gives

`Using Anaconda Cloud api site https://api.anaconda.org`
`Run 'anaconda show <USER/PACKAGE>' to get more details:`
`Packages:`
`     Name                      |  Version | Package Types   | Platforms`
`     ------------------------- |   ------ | --------------- | ---------------`

     Clyde_Fare/pyhull         |    1.5.3 | conda           | linux-64
                                          : A Python wrapper to Qhull (http://www.qhull.org/) for the computation of the convex hull, Delaunay triangulation and Voronoi diagram

     auto/pyhull               |    1.4.3 | conda           | linux-64
                                          : https://github.com/shyuep/pyhull

     derickl/pyhull            |    1.5.4 | conda           | osx-64
                                          : A Python wrapper to Qhull (http://www.qhull.org/) for the computation of the convex hull, Delaunay triangulation and Voronoi diagram

     mhein/pyhull              |    1.5.4 | conda           | osx-64
                                          : A Python wrapper to Qhull (http://www.qhull.org/) for the computation of the convex hull, Delaunay triangulation and Voronoi diagram

`Found 4 packages`

Attempts to install these packages on windows 7 64 bit fail. (obviously) Is there a package for win64?

**Comment by stephenakearns** [comment]
Doing a quick search on Anaconda Cloud, I'm seeing the same thing - no Win64 packages - https://anaconda.org/search?q=pyhull  - @csoja thoughts?

**Comment by csoja** [comment]
Pyhull is not one of the packages currently included with Anaconda.  If a search of Anaconda Cloud hasn't listed a Windows version - it means no one else has created a public Windows conda package and uploaded it to Anaconda Cloud.  You could attempt to build one yourself.  Here is a link to the conda-build documentation: http://conda.pydata.org/docs/building/build.html  Or you could trying using pip to install it.

**Comment by stephenakearns** [comment]
@bwanaaa - closing this issue - please reopen if you feel like the issue was not addressed.
