### ISSUE TITLE
Cannot activate MKL license

### ISSUE THREAD

**Issue by asifm** [Anaconda-Server/support#25]
I'm pointed from https://anaconda.org/asifm/settings/add-ons to https://docs.continuum.io/advanced-installation to activate my MKL license. But the latter url doesn't work.

**Comment by dsludwig** [comment]
@electronwill is this related to the doc replatform? I still see the file in the repository.

**Comment by electronwill** [comment]
Yes, it probably is. Thank you for pointing this out, and I'll get it fixed as soon as possible. In the meantime, these are the instructions that were posted there:


Mac & Linux

The ~/.continuum directory is a hidden directory (also known as a folder) in your home directory, which means that it only appears in the Finder or file explorer programs such as Nautilus or Konqueror if a "show hidden files and directories" option is enabled, and does not appear in the output of the "ls" command but does appear in the output of "ls -a". We use a hidden directory to avoid cluttering the appearance of your home directory and to help protect your license files from accidental changes or deletion.

1. Open a terminal window and run "ls -a" to list the files and directories in your home directory, and see if there is a directory named ".continuum".

2. If there is no directory named ".continuum", use "mkdir" to make one.

mkdir .continuum

3. Use the "ls" command OR a file explorer program to find the directory containing the license file. Usually this will be the "Downloads" folder in the home directory. Use "cd" to navigate to this directory:

cd Downloads

4. Find and copy the license filename. Use "mv" to move the license file to the directory "~/.continuum":

mv license_accelerate_1234.txt ~/.continuum

NOTE: Replace "license_accelerate_1234.txt" with the actual name of your license file.

5. If you did not previously install a 30-day trial, run these commands:

NOTE: If you did previously install a 30-day trial, you do not need to run these commands, but running them is harmless.

conda update conda
conda install your_first_package_name
conda install your_second_package_name

NOTE: Replace "your_first_package_name" and "your_second_package_name" with the names of your packages, such as "iopro" or "accelerate".

6. Run python and make sure the startup message says that it is Anaconda Python. In the python interpreter, run:

import your_first_package_name
import your_second_package_name

NOTE: Replace "your_first_package_name" and "your_second_package_name" with the names of your packages, such as "iopro", "numbapro", or "mkl".

Your license is now installed.

Windows XP & Vista & 7 & 8

The .continuum directory is a hidden folder in your home directory, which means that it only appears in Windows Explorer if the "show hidden files and folders" option is enabled. We use a hidden folder to avoid cluttering the appearance of your home directory and to help protect your license files from accidental changes or deletion.

1. Open a Command Prompt window and run "dir" to list the files and folders in your home directory, and see if there is a folder named ".continuum". Typically in Windows XP your home directory will be "C:\Documents and Settings\<Your User Name>", in Windows Vista it will be "C:\Documents and Settings\User\<Your User Name>" and in Windows 7 & 8 it will be "C:\Users\<Your User Name>".

2. If there is no folder named ".continuum", run "mkdir .continuum" to create it.

3. Use the "dir" command OR Windows Explorer to find the folder containing the license file. Usually this will be the "Downloads" folder in the home directory.

4. Use the "copy" command OR Windows Explorer to copy the license file into the ".continuum" directory. If the license file is in the "Downloads" folder, run "copy Downloads/license_accelerate_1234.txt .continuum"

NOTE: Replace "license_accelerate_1234.txt" with the actual name of your license file.

5. If you did not previously install a 30-day trial, run these commands:

NOTE: If you did previously install a 30-day trial, you do not need to run these commands, but running them is harmless.

conda update conda
conda install your_first_package_name
conda install your_second_package_name
NOTE: Replace "your_first_package_name" and "your_second_package_name" with the names of your packages, such as "iopro" or "accelerate".

6. Run python and make sure the startup message says that it is Anaconda Python. In the python interpreter, run:

import your_first_package_name
import your_second_package_name

NOTE: Replace "your_first_package_name" and "your_second_package_name" with the names of your packages, such as "iopro" or "numbapro".

Your license is now installed.

Problems, questions? Please contact sales@continuum.io.

**Comment by asifm** [comment]
Thanks for the quick and helpful response. 
In case it helps, I found another broken link: https://docs.continuum.io/mkl-service/index.html

**Comment by electronwill** [comment]
Oh, thank you-- yes, that is useful. Please mention it here if you find any others. The contents of that page should be as follows:

```
===========
mkl-service
===========

This package exposes a few functions which are declared in mkl_service.h.
The main purpose of the package is to allow the user to change the number
of CPU's MKL is using at runtime.


Example:
--------

In this small example, we first query how many CPU are being used, and then
change this number.

   >>> import mkl
   >>> mkl.get_max_threads()
   2
   >>> mkl.set_num_threads(1)
   >>> mkl.get_max_threads()
   1


Reference
---------

**mkl service functions:**

``mkl.get_cpu_clocks()`` -> int
   Return the CPU clocks as an integer.


``mkl.get_cpu_frequency()`` -> float
   Return CPU frequency in GHz as a float.


``mkl.get_max_threads()`` -> int
   Return the number of threads Intel MKL is targeting for parallelism.


``mkl.get_version_string()`` -> str
   Return the MKL library version information as a string.


``mkl.mem_stat(n)`` -> int
   Returns an amount of memory, allocated by the MKL Memory Allocator.


``mkl.set_num_threads(n)``
   Set the number of threads MKL should use.  This is only a hint, and no
   guaranteed is made this number of threads will actually be used.
   This function takes precedence over the environment variable
   MKL_NUM_THREADS.
```

**Comment by electronwill** [comment]
OK, those two links should work now. If you find any other broken links, please let me know.
