### ISSUE TITLE
Unable to see upvoters of a package

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/support#33]
See this package as an example. ( https://anaconda.org/conda-forge/icu/upvoters )
Picture below.

<img width="1554" alt="screen shot 2016-04-05 at 20 27 42" src="https://cloud.githubusercontent.com/assets/3019665/14302237/c34b7dc4-fb6c-11e5-8ea2-178312ef1923.png">

**Comment by rafaelhbarros** [comment]
page returns empty list now, instead of the <p> tag

**Comment by stephenakearns** [comment]
fixed in our development env. @dsludwig to attach PR

**Comment by dsludwig** [comment]
This was fixed in https://github.com/Anaconda-Server/anaconda-server/pull/1872. It will be released in the next version (in about 2 weeks).

Thanks for reporting @jakirkham!

**Comment by jakirkham** [comment]
While the situation has improved here, it is not totally resolved. This is the situation I see when click to see who starred a package.

<img width="1554" alt="screen shot 2016-05-27 at 10 59 13" src="https://cloud.githubusercontent.com/assets/3019665/15611835/2c94cbf4-23fa-11e6-9db4-c53ccbff4dde.png">
