### ISSUE TITLE
endlocal statement in activate.bat prevents environment variables being propogates

### ISSUE THREAD

**Issue by gillins** [Anaconda-Server/support#4]
Just testing the latest gdal build. There is a gdal-activate.bat that gets properly called to set %GDAL_DATA% but this does not get returned to the user's environment. I think this is due to the endlocal statement preventing set variables getting returned to the caller.

This is easy to test by trying to activate an environment with gdal in it and testing the value to %GDAL_DATA%

**Comment by srossross** [comment]
@csoja when you have a moment can you make an update on this issue?

**Comment by stephenakearns** [comment]
Hi @gillins - to clarify, you've created an environment with gdal installed and then when you go to conda env source activate you get this error condition where the env variable isn't being set?

**Comment by gillins** [comment]
Correct.

I can also confirm that putting an endlocal statement in gdal-activate.bat didn't seem to help.

**Comment by stephenakearns** [comment]
This issue was moved to conda/conda-env#218
