### ISSUE TITLE
Anaconda install stall

### ISSUE THREAD

**Issue by ImageHub** [Anaconda-Server/support#5]
I noticed the installation stalled for several minutes every time it is writing an *.exe to the Anaconda2/Scripts directory. Why would this be? Especially since these files are rather small.

**Comment by stephenakearns** [comment]
hi @ImageHub - just confirming - I'm assuming the installation you're referring to is  the installation of the Anaconda Distribution? (or miniConda)

**Comment by stephenakearns** [comment]
No response - closing this issue. @ImageHub if you are still having issues installing the Anaconda Distribution, please log an issue in this repo: https://github.com/continuumio/anaconda-issues/issues
