### ISSUE TITLE
Pagination incorrect on pages listing files in a conda channel/package

### ISSUE THREAD

**Issue by mwcraig** [Anaconda-Server/support#6]
The issue is that a second page is always listed in the navigation tools at the bottom of the page even when there is not a second page of files.

See: https://anaconda.org/mwcraig/vpython/files

and the page navigation buttons at the bottom of it, which indicates a second page...which is empty.

<img width="174" alt="downloads_ _mwcraig_vpython" src="https://cloud.githubusercontent.com/assets/1147167/11857026/9114876e-a41a-11e5-9067-d3ccc79e40ce.png">

**Comment by stephenakearns** [comment]
Thanks for reporting this @mwcraig - adding this to our backlog and will notify when it's been resolved.

**Comment by stephenakearns** [comment]
@mwcraig, the fix for this went into production yesterday (v2.12.3) - can you review and let us know if it's not fixed. closing but happy to reopen.
